/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Anthony Giron
 */
public class frm_calculadora extends javax.swing.JFrame {


    public frm_calculadora() {
        initComponents();

    }
    private double currentResult = 0;
    private String currentInput = ""; 
    private String operator = ""; 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_pantalla = new javax.swing.JTextField();
        tf_0 = new javax.swing.JButton();
        tf_1 = new javax.swing.JButton();
        tf_2 = new javax.swing.JButton();
        tf_3 = new javax.swing.JButton();
        tf_4 = new javax.swing.JButton();
        tf_5 = new javax.swing.JButton();
        tf_6 = new javax.swing.JButton();
        tf_7 = new javax.swing.JButton();
        tf_8 = new javax.swing.JButton();
        tf_9 = new javax.swing.JButton();
        tf_div = new javax.swing.JButton();
        tf_multi = new javax.swing.JButton();
        tf_restar = new javax.swing.JButton();
        tf_suma = new javax.swing.JButton();
        tf_punto = new javax.swing.JButton();
        tf_igual = new javax.swing.JButton();
        tf_borrar = new javax.swing.JButton();
        tf_borrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));

        tf_pantalla.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_pantalla.setAutoscrolls(false);
        tf_pantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        tf_pantalla.setEnabled(false);
        tf_pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pantallaActionPerformed(evt);
            }
        });

        tf_0.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_0.setText("0");
        tf_0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_0ActionPerformed(evt);
            }
        });

        tf_1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_1.setText("1");
        tf_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_1ActionPerformed(evt);
            }
        });

        tf_2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_2.setText("2");
        tf_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_2ActionPerformed(evt);
            }
        });

        tf_3.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_3.setText("3");
        tf_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_3ActionPerformed(evt);
            }
        });

        tf_4.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_4.setText("4");
        tf_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_4ActionPerformed(evt);
            }
        });

        tf_5.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_5.setText("5");
        tf_5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_5ActionPerformed(evt);
            }
        });

        tf_6.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_6.setText("6");
        tf_6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_6ActionPerformed(evt);
            }
        });

        tf_7.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_7.setText("7");
        tf_7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_7ActionPerformed(evt);
            }
        });

        tf_8.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_8.setText("8");
        tf_8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_8ActionPerformed(evt);
            }
        });

        tf_9.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_9.setText("9");
        tf_9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_9ActionPerformed(evt);
            }
        });

        tf_div.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_div.setText("/");
        tf_div.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_div.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_divActionPerformed(evt);
            }
        });

        tf_multi.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_multi.setText("*");
        tf_multi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_multi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_multiActionPerformed(evt);
            }
        });

        tf_restar.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_restar.setText("-");
        tf_restar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_restar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_restarActionPerformed(evt);
            }
        });

        tf_suma.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_suma.setText("+");
        tf_suma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_suma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sumaActionPerformed(evt);
            }
        });

        tf_punto.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_punto.setText(".");
        tf_punto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_punto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_puntoActionPerformed(evt);
            }
        });

        tf_igual.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tf_igual.setText("=");
        tf_igual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_igual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_igualActionPerformed(evt);
            }
        });

        tf_borrar.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        tf_borrar.setText("Retroceder");
        tf_borrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrarActionPerformed(evt);
            }
        });

        tf_borrar1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        tf_borrar1.setText("Borrar");
        tf_borrar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        tf_borrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tf_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_restar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_div, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_0, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_borrar)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tf_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_div, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_restar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tf_pantalla.getAccessibleContext().setAccessibleName("");
        tf_pantalla.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_7ActionPerformed
        // TODO add your handling code here:
         appendNumber("7");
    }//GEN-LAST:event_tf_7ActionPerformed

    private void tf_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_8ActionPerformed
        // TODO add your handling code here:
         appendNumber("8");
    }//GEN-LAST:event_tf_8ActionPerformed

    private void tf_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_9ActionPerformed
        // TODO add your handling code here:
         appendNumber("9");
    }//GEN-LAST:event_tf_9ActionPerformed

    private void tf_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_divActionPerformed
        // TODO add your handling code here:
         setOperator("/");
    }//GEN-LAST:event_tf_divActionPerformed

    private void tf_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_4ActionPerformed
        // TODO add your handling code here:
         appendNumber("4");
    }//GEN-LAST:event_tf_4ActionPerformed

    private void tf_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_5ActionPerformed
        // TODO add your handling code here:
         appendNumber("5");
    }//GEN-LAST:event_tf_5ActionPerformed

    private void tf_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_6ActionPerformed
        // TODO add your handling code here
        appendNumber("6");
    }//GEN-LAST:event_tf_6ActionPerformed

    private void tf_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_multiActionPerformed
        // TODO add your handling code here:
         setOperator("*");
    }//GEN-LAST:event_tf_multiActionPerformed

    private void tf_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_1ActionPerformed
        // TODO add your handling code here:
         appendNumber("1");
    }//GEN-LAST:event_tf_1ActionPerformed

    private void tf_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_2ActionPerformed
        // TODO add your handling code here:
         appendNumber("2");
    }//GEN-LAST:event_tf_2ActionPerformed

    private void tf_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_3ActionPerformed
        // TODO add your handling code here:
         appendNumber("3");
    }//GEN-LAST:event_tf_3ActionPerformed

    private void tf_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_restarActionPerformed
        // TODO add your handling code here:
         setOperator("-");
    }//GEN-LAST:event_tf_restarActionPerformed

    private void tf_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_0ActionPerformed
        // TODO add your handling code here:
         appendNumber("0");
    }//GEN-LAST:event_tf_0ActionPerformed

    private void tf_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_puntoActionPerformed
        // TODO add your handling code here:
         appendNumber(".");
    }//GEN-LAST:event_tf_puntoActionPerformed

    private void tf_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sumaActionPerformed
        // TODO add your handling code here:
         setOperator("+");
    }//GEN-LAST:event_tf_sumaActionPerformed

    private void tf_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_igualActionPerformed
        // TODO add your handling code here:
    calculateResult();
    }//GEN-LAST:event_tf_igualActionPerformed

    private void tf_pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pantallaActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_tf_pantallaActionPerformed

    private void tf_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrarActionPerformed
        // TODO add your handling code here:
        if (!currentInput.isEmpty()) {
        currentInput = currentInput.substring(0, currentInput.length() - 1);
        tf_pantalla.setText(currentInput);
    }
    }//GEN-LAST:event_tf_borrarActionPerformed

    private void tf_borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrar1ActionPerformed
        // TODO add your handling code here:
         currentInput = "";
    currentResult = 0;
    operator = "";
    tf_pantalla.setText("");
    }//GEN-LAST:event_tf_borrar1ActionPerformed
private void appendToDisplay(String value) {
        currentInput += value;
        tf_pantalla.setText(currentInput);
        
    
    }
private void appendNumber(String number) {
        currentInput += number;
        tf_pantalla.setText(currentInput);
}
    private void setOperator(String op) {
        if (!currentInput.isEmpty()) {
            currentResult = Double.parseDouble(currentInput);
            currentInput = "";
            operator = op;
        }
    }
    private void calculateResult(){
       if(!currentInput.isEmpty()&& !operator.isEmpty() ){
           double inputNumber = Double.parseDouble(currentInput);
           switch(operator){
               case "+":
                   currentResult += inputNumber;
                   break;
                   case "-":
                   currentResult -= inputNumber;
                   break;
                      case "*":
                   currentResult *= inputNumber;
                   break;
                      case "/":
                   if (inputNumber != 0){
                       currentResult /= inputNumber;
                   } else{
                       tf_pantalla.setText("Error");
                       return;
                   }
                   break;
           }
           
       }
         tf_pantalla.setText(Double.toString(currentResult));
         currentInput = Double.toString(currentResult);
         operator = "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton tf_0;
    private javax.swing.JButton tf_1;
    private javax.swing.JButton tf_2;
    private javax.swing.JButton tf_3;
    private javax.swing.JButton tf_4;
    private javax.swing.JButton tf_5;
    private javax.swing.JButton tf_6;
    private javax.swing.JButton tf_7;
    private javax.swing.JButton tf_8;
    private javax.swing.JButton tf_9;
    private javax.swing.JButton tf_borrar;
    private javax.swing.JButton tf_borrar1;
    private javax.swing.JButton tf_div;
    private javax.swing.JButton tf_igual;
    private javax.swing.JButton tf_multi;
    private javax.swing.JTextField tf_pantalla;
    private javax.swing.JButton tf_punto;
    private javax.swing.JButton tf_restar;
    private javax.swing.JButton tf_suma;
    // End of variables declaration//GEN-END:variables
}
